# Generated by Django 4.1.1 on 2022-10-07 20:40

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=1024, null=True)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                ("phone", models.CharField(blank=True, max_length=32, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "avatar",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=dashboard.models._set_uploaded_filename,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
