# Generated by Django 4.1.1 on 2022-10-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_email_comment_name_alter_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
