# Generated by Django 4.1.1 on 2022-10-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContatcUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("subject", models.CharField(max_length=128)),
                ("message", models.CharField(max_length=2048)),
                ("is_seen", models.BooleanField(default=False)),
            ],
        ),
    ]
