# Generated by Django 4.1.1 on 2022-10-20 13:15

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contatcus_date_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="SliderContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("small_title", models.CharField(max_length=128)),
                ("big_title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=256)),
                (
                    "image",
                    models.FileField(upload_to=home.models._set_uploaded_filename),
                ),
                ("cta_title", models.CharField(max_length=128)),
                ("cta_link", models.CharField(max_length=256)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
