# Generated by Django 4.1.1 on 2022-11-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_slidercontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="contatcus",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
