# Generated by Django 4.1.1 on 2022-10-20 12:18

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_review_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="catalog1",
            field=models.FileField(
                blank=True, null=True, upload_to=shop.models._set_uploaded_filename
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="catalog2",
            field=models.FileField(
                blank=True, null=True, upload_to=shop.models._set_uploaded_filename
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="catalog3",
            field=models.FileField(
                blank=True, null=True, upload_to=shop.models._set_uploaded_filename
            ),
        ),
    ]
