# Generated by Django 4.1.1 on 2022-11-04 06:31

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0004_product_catalog1_product_catalog2_product_catalog3"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_prod_cats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "prod_categories",
                "unique_together": {("slug",)},
            },
        ),
        migrations.CreateModel(
            name="ProductProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title", unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("content", models.TextField()),
                ("features", models.TextField(blank=True, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "image_cover",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=shop.models._set_uploaded_filename,
                    ),
                ),
                (
                    "catalog1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=shop.models._set_uploaded_filename,
                    ),
                ),
                (
                    "catalog2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=shop.models._set_uploaded_filename,
                    ),
                ),
                (
                    "catalog3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=shop.models._set_uploaded_filename,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prod_products",
                        to="shop.categoryprod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review", models.TextField()),
                ("rate", models.FloatField(default=3)),
                ("name", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod_reviews",
                        to="shop.productprod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImagesProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=shop.models._set_uploaded_filename,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prod_images",
                        to="shop.productprod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
