# Generated by Django 4.1.1 on 2022-11-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_rename_id_invoice_new_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="new_id",
            new_name="id",
        ),
    ]
