# Generated by Django 4.1.1 on 2022-12-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_payment_date_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="productprod",
            name="video",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
