# Generated by Django 5.0.2 on 2024-02-29 12:58

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_productprod_the_drive_motor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprod',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=shop.models._set_uploaded_filename),
        ),
    ]
