# Generated by Django 5.0.2 on 2024-03-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_productprod_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprod',
            name='The_drive_motor',
        ),
        migrations.AddField(
            model_name='productprod',
            name='abrasive_hopper',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Abrasive hopper'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='abrasive_tank',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='مخزن ماده ساینده'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='axis_a_b_movement_system',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم حرکتی محور A & B'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='axis_x_y_movement_system',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم حرکتی محور X & Y'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='axis_z_movement_system',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم حرکتی محور Z'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='cable_thickness_cable_length',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='ضخامت کابل / طول کابل'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='computer_system',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم کامپیوتری'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='controller_maximum_error',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='حداکثر خطای سیستم کنترلر'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='controller_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='نوع کنترلر'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='cutting_milling_head_count',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='تعداد هد برشکاری/فرزکاری'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='cutting_milling_thickness_range',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='محدوده ضخامت برشکاری / فرزکاری'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='drilling_accuracy',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='دقت سوراخکاری دستگاه'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='drive_motor',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='موتور محرک دستگاه'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='drive_motor_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='نوع موتورهای حرکتی'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='electrical_panel',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='تابلو برق'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='g_code_reading_capability',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='قابلیت خواندن G-code'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='gearbox_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='نوع سیستم گیربکس'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='glass_easy_movement_system',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم حرکت آسان شیشه'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='glass_separation_system_after_cutting',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم جداسازی شیشه پس از برش'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='height_control_system',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم کنترل ارتفاع'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='jack_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='نوع جک ها'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='laser_technology_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='نوع تکنولوژی لیزر'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='machine_maximum_error',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='حداکثر خطای ماشین'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='machine_movement_accuracy',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='دقت حرکتی دستگاه'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='maximum_disk_diameter',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='حداکثر قطر دیسک'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='maximum_laser_power',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='حداکثر توان لیزر'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='maximum_rotary_part_opening_length',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='حداکثر طول باز شدن قسمت روتاری'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='mechanism_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='نوع مکانیزم'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='operating_voltage',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='ولتاژ کاری'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='pipe_boring_dimensions',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='ابعاد مفید لوله بر'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='plasma_installation_prerequisites',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='پیش نیاز نصب پلاسما'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='power_transmission_system',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سیستم انتقال نیرو'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='rotary_axis_c',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='محور C روتاری'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='rotary_gearboxes',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='گیربکس های روتاری'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='spindle_distance_between_axes',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='آکس بین اسپیندل ها'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='spindle_type',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='نوع اسپیندل'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='total_weight',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='وزن کلی دستگاه'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='uniform_spraying_material_reservoir',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='مخزن پاشش یکنواخت ماده ساینده'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='water_collection_tank',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='حوضچه جمع آوری آب'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='water_pump_capacity',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='ظرفیت پمپ آب'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='waterjet_pump_power',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='توان پمپ واترجت'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='worktable_dimensions',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='ابعاد مفید میزکار'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='x_y_axis_speed',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سرعت حرکتی محور X & Y'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='z_axis_speed',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='سرعت حرکتی محور Z'),
        ),
        migrations.AddField(
            model_name='productprod',
            name='z_axis_working_range',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='محدوده کاری محور Z'),
        ),
        migrations.AlterField(
            model_name='productprod',
            name='longitudinal_movement',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='موتور اصلی حرکت طولی'),
        ),
        migrations.AlterField(
            model_name='productprod',
            name='pusher_engines',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='موتور های فشار دهنده'),
        ),
    ]
